### ISSUE TITLE
Cannot find module 'watchify'

### ISSUE THREAD

**Issue by chadwatson** [40Digits/gulp-starter#1]
I got this after running `npm install` successfully.

```
Chads-MacBook-Pro:wp-theme chadwatson$ gulp

Error: Cannot find module 'watchify'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/chadwatson/Projects/helperpress-test/wp-theme/_gulp/tasks/browserify.js:14:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by chuckmo** [comment]
I think this is result of watchify not being in package.json

**Comment by prichey** [comment]
@chadwatson Are you still seeing this? I haven't ran into the issue between several new setups. If this isn't an issue any longer let's close it.

**Comment by chadwatson** [comment]
@prichey I had to install it globally then it worked fine after that. But I think @chuckmo is right. Doesn't look like it's included in package.json. That's what was causing the problem for me, and I assume that anyone who doesn't have it installed globally already will continue to run into the same issues I was.

**Comment by prichey** [comment]
I just checked and I don't have watchify install globally. Do you still get the error when running it in that directory? I just ran `npm ls | grep watchify` from the directory, which should show if watchify is a dependency and it doesn't look like that's the case. I'm thinking it was removed.

**Comment by besimhu** [comment]
Yeah, been fixed long time ago, I just never closed it out. 

Basically chad had a beta version, and my system had watchify running where as his didn't. I just ended up removing it from my dependency list while he still needed it.
